name: base_app
description: POC
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  module_external_dependencies:
    path: '../module_external_dependencies'

  module_commons:
    path: '../module_commons'

  module_debit:
    path: '../module_debit'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - fonts/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono/RobotoMono-Thin.ttf
          weight: 100
        - asset: fonts/RobotoMono/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: fonts/RobotoMono/RobotoMono-Light.ttf
          weight: 300
        - asset: fonts/RobotoMono/RobotoMono-Regular.ttf
          weight: 400
        - asset: fonts/RobotoMono/RobotoMono-Medium.ttf
          weight: 500
        - asset: fonts/RobotoMono/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: fonts/RobotoMono/RobotoMono-Bold.ttf
          weight: 700
